spring:
  application:
    name: microservice-customer

  devtools:
    restart:
      enabled: true
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customer

server:
  port: 8080
  servlet:
    context-path: /customer